### ISSUE TITLE
Kafka inter-broker protocol

### ISSUE THREAD

**Issue by drywheat** [orgsync-cookbooks/os-kafka#1]
@hadronzoo can we bump the protocol version here back to **0.9.0.0**?

https://github.com/orgsync-cookbooks/os-kafka/blob/master/attributes/default.rb#L30

/cc @lmickh

**Comment by hadronzoo** [comment]
Yes, we should be OK now that poseidon is gone. I don't think it was the root problem.

**Comment by drywheat** [comment]
Excellent. Thank you.
